namespace QuanLyDeTai.PKHCN.QuanLyDT
{
    partial class modal
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(modal));
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties41 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties42 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties43 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties44 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties45 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties46 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties47 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties48 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges3 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges4 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties49 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties50 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties51 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties52 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties53 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties54 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties55 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties56 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties57 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties58 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties59 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties60 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties61 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties62 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties63 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties64 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties65 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties66 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties67 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties68 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties69 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties70 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties71 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties72 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties73 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties74 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties75 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties76 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties77 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties78 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties79 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties80 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            this.Cap = new Bunifu.UI.WinForms.BunifuTextBox();
            this.MBM = new Bunifu.UI.WinForms.BunifuTextBox();
            this.HT = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.bunifuButton2 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.CN = new Bunifu.UI.WinForms.BunifuTextBox();
            this.TT = new Guna.UI2.WinForms.Guna2ComboBox();
            this.TenDT = new Bunifu.UI.WinForms.BunifuTextBox();
            this.MDT = new Bunifu.UI.WinForms.BunifuTextBox();
            this.panel2 = new System.Windows.Forms.Panel();
            this.NgayBD = new Bunifu.UI.WinForms.BunifuTextBox();
            this.NgayNT = new Bunifu.UI.WinForms.BunifuTextBox();
            this.TienDo = new Bunifu.UI.WinForms.BunifuTextBox();
            this.KQ = new Bunifu.UI.WinForms.BunifuTextBox();
            this.LSP = new Bunifu.UI.WinForms.BunifuTextBox();
            this.guna2HtmlLabel2 = new Guna.UI2.WinForms.Guna2HtmlLabel();
            this.panel2.SuspendLayout();
            this.SuspendLayout();
            // 
            // Cap
            // 
            this.Cap.AcceptsReturn = false;
            this.Cap.AcceptsTab = false;
            this.Cap.AnimationSpeed = 200;
            this.Cap.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.Cap.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.Cap.BackColor = System.Drawing.Color.Transparent;
            this.Cap.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("Cap.BackgroundImage")));
            this.Cap.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.Cap.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.Cap.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.Cap.BorderColorIdle = System.Drawing.Color.Silver;
            this.Cap.BorderRadius = 1;
            this.Cap.BorderThickness = 1;
            this.Cap.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.Cap.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.Cap.DefaultFont = new System.Drawing.Font("Times New Roman", 9F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.Cap.DefaultText = "";
            this.Cap.FillColor = System.Drawing.Color.White;
            this.Cap.HideSelection = true;
            this.Cap.IconLeft = null;
            this.Cap.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.Cap.IconPadding = 10;
            this.Cap.IconRight = null;
            this.Cap.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.Cap.Lines = new string[0];
            this.Cap.Location = new System.Drawing.Point(173, 248);
            this.Cap.MaxLength = 32767;
            this.Cap.MinimumSize = new System.Drawing.Size(1, 1);
            this.Cap.Modified = false;
            this.Cap.Multiline = false;
            this.Cap.Name = "Cap";
            stateProperties41.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties41.FillColor = System.Drawing.Color.Empty;
            stateProperties41.ForeColor = System.Drawing.Color.Empty;
            stateProperties41.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.Cap.OnActiveState = stateProperties41;
            stateProperties42.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties42.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties42.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties42.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.Cap.OnDisabledState = stateProperties42;
            stateProperties43.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties43.FillColor = System.Drawing.Color.Empty;
            stateProperties43.ForeColor = System.Drawing.Color.Empty;
            stateProperties43.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.Cap.OnHoverState = stateProperties43;
            stateProperties44.BorderColor = System.Drawing.Color.Silver;
            stateProperties44.FillColor = System.Drawing.Color.White;
            stateProperties44.ForeColor = System.Drawing.Color.Empty;
            stateProperties44.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.Cap.OnIdleState = stateProperties44;
            this.Cap.Padding = new System.Windows.Forms.Padding(3);
            this.Cap.PasswordChar = '\0';
            this.Cap.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.Cap.PlaceholderText = "Nhập cấp";
            this.Cap.ReadOnly = false;
            this.Cap.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.Cap.SelectedText = "";
            this.Cap.SelectionLength = 0;
            this.Cap.SelectionStart = 0;
            this.Cap.ShortcutsEnabled = true;
            this.Cap.Size = new System.Drawing.Size(260, 34);
            this.Cap.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.Cap.TabIndex = 3;
            this.Cap.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.Cap.TextMarginBottom = 0;
            this.Cap.TextMarginLeft = 3;
            this.Cap.TextMarginTop = 0;
            this.Cap.TextPlaceholder = "Nhập cấp";
            this.Cap.UseSystemPasswordChar = false;
            this.Cap.WordWrap = true;
            // 
            // MBM
            // 
            this.MBM.AcceptsReturn = false;
            this.MBM.AcceptsTab = false;
            this.MBM.AnimationSpeed = 200;
            this.MBM.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.MBM.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.MBM.BackColor = System.Drawing.Color.Transparent;
            this.MBM.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("MBM.BackgroundImage")));
            this.MBM.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.MBM.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.MBM.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.MBM.BorderColorIdle = System.Drawing.Color.Silver;
            this.MBM.BorderRadius = 1;
            this.MBM.BorderThickness = 1;
            this.MBM.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.MBM.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.MBM.DefaultFont = new System.Drawing.Font("Times New Roman", 9F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.MBM.DefaultText = "";
            this.MBM.FillColor = System.Drawing.Color.White;
            this.MBM.HideSelection = true;
            this.MBM.IconLeft = null;
            this.MBM.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.MBM.IconPadding = 10;
            this.MBM.IconRight = null;
            this.MBM.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.MBM.Lines = new string[0];
            this.MBM.Location = new System.Drawing.Point(907, 126);
            this.MBM.MaxLength = 32767;
            this.MBM.MinimumSize = new System.Drawing.Size(1, 1);
            this.MBM.Modified = false;
            this.MBM.Multiline = false;
            this.MBM.Name = "MBM";
            stateProperties45.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties45.FillColor = System.Drawing.Color.Empty;
            stateProperties45.ForeColor = System.Drawing.Color.Empty;
            stateProperties45.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.MBM.OnActiveState = stateProperties45;
            stateProperties46.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties46.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties46.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties46.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.MBM.OnDisabledState = stateProperties46;
            stateProperties47.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties47.FillColor = System.Drawing.Color.Empty;
            stateProperties47.ForeColor = System.Drawing.Color.Empty;
            stateProperties47.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.MBM.OnHoverState = stateProperties47;
            stateProperties48.BorderColor = System.Drawing.Color.Silver;
            stateProperties48.FillColor = System.Drawing.Color.White;
            stateProperties48.ForeColor = System.Drawing.Color.Empty;
            stateProperties48.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.MBM.OnIdleState = stateProperties48;
            this.MBM.Padding = new System.Windows.Forms.Padding(3);
            this.MBM.PasswordChar = '\0';
            this.MBM.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.MBM.PlaceholderText = "Nhập mã bộ môn";
            this.MBM.ReadOnly = false;
            this.MBM.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.MBM.SelectedText = "";
            this.MBM.SelectionLength = 0;
            this.MBM.SelectionStart = 0;
            this.MBM.ShortcutsEnabled = true;
            this.MBM.Size = new System.Drawing.Size(260, 34);
            this.MBM.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.MBM.TabIndex = 11;
            this.MBM.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.MBM.TextMarginBottom = 0;
            this.MBM.TextMarginLeft = 3;
            this.MBM.TextMarginTop = 0;
            this.MBM.TextPlaceholder = "Nhập mã bộ môn";
            this.MBM.UseSystemPasswordChar = false;
            this.MBM.WordWrap = true;
            // 
            // HT
            // 
            this.HT.AllowAnimations = true;
            this.HT.AllowMouseEffects = true;
            this.HT.AllowToggling = false;
            this.HT.AnimationSpeed = 200;
            this.HT.AutoGenerateColors = false;
            this.HT.AutoRoundBorders = false;
            this.HT.AutoSizeLeftIcon = true;
            this.HT.AutoSizeRightIcon = true;
            this.HT.BackColor = System.Drawing.Color.Transparent;
            this.HT.BackColor1 = System.Drawing.Color.LimeGreen;
            this.HT.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("HT.BackgroundImage")));
            this.HT.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.HT.ButtonText = "Lưu";
            this.HT.ButtonTextMarginLeft = 0;
            this.HT.ColorContrastOnClick = 45;
            this.HT.ColorContrastOnHover = 45;
            this.HT.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges3.BottomLeft = true;
            borderEdges3.BottomRight = true;
            borderEdges3.TopLeft = true;
            borderEdges3.TopRight = true;
            this.HT.CustomizableEdges = borderEdges3;
            this.HT.DialogResult = System.Windows.Forms.DialogResult.None;
            this.HT.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.HT.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.HT.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.HT.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.HT.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.HT.ForeColor = System.Drawing.Color.White;
            this.HT.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.HT.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.HT.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.HT.IconMarginLeft = 11;
            this.HT.IconPadding = 10;
            this.HT.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.HT.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.HT.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.HT.IconSize = 25;
            this.HT.IdleBorderColor = System.Drawing.Color.LimeGreen;
            this.HT.IdleBorderRadius = 1;
            this.HT.IdleBorderThickness = 1;
            this.HT.IdleFillColor = System.Drawing.Color.LimeGreen;
            this.HT.IdleIconLeftImage = null;
            this.HT.IdleIconRightImage = null;
            this.HT.IndicateFocus = false;
            this.HT.Location = new System.Drawing.Point(173, 581);
            this.HT.Name = "HT";
            this.HT.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.HT.OnDisabledState.BorderRadius = 1;
            this.HT.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.HT.OnDisabledState.BorderThickness = 1;
            this.HT.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.HT.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.HT.OnDisabledState.IconLeftImage = null;
            this.HT.OnDisabledState.IconRightImage = null;
            this.HT.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.HT.onHoverState.BorderRadius = 1;
            this.HT.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.HT.onHoverState.BorderThickness = 1;
            this.HT.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.HT.onHoverState.ForeColor = System.Drawing.Color.White;
            this.HT.onHoverState.IconLeftImage = null;
            this.HT.onHoverState.IconRightImage = null;
            this.HT.OnIdleState.BorderColor = System.Drawing.Color.LimeGreen;
            this.HT.OnIdleState.BorderRadius = 1;
            this.HT.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.HT.OnIdleState.BorderThickness = 1;
            this.HT.OnIdleState.FillColor = System.Drawing.Color.LimeGreen;
            this.HT.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.HT.OnIdleState.IconLeftImage = null;
            this.HT.OnIdleState.IconRightImage = null;
            this.HT.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.HT.OnPressedState.BorderRadius = 1;
            this.HT.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.HT.OnPressedState.BorderThickness = 1;
            this.HT.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.HT.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.HT.OnPressedState.IconLeftImage = null;
            this.HT.OnPressedState.IconRightImage = null;
            this.HT.Size = new System.Drawing.Size(89, 39);
            this.HT.TabIndex = 12;
            this.HT.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.HT.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.HT.TextMarginLeft = 0;
            this.HT.TextPadding = new System.Windows.Forms.Padding(0);
            this.HT.UseDefaultRadiusAndThickness = true;
            this.HT.Click += new System.EventHandler(this.HT_Click);
            // 
            // bunifuButton2
            // 
            this.bunifuButton2.AllowAnimations = true;
            this.bunifuButton2.AllowMouseEffects = true;
            this.bunifuButton2.AllowToggling = false;
            this.bunifuButton2.AnimationSpeed = 200;
            this.bunifuButton2.AutoGenerateColors = false;
            this.bunifuButton2.AutoRoundBorders = false;
            this.bunifuButton2.AutoSizeLeftIcon = true;
            this.bunifuButton2.AutoSizeRightIcon = true;
            this.bunifuButton2.BackColor = System.Drawing.Color.Transparent;
            this.bunifuButton2.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(192)))), ((int)(((byte)(64)))), ((int)(((byte)(0)))));
            this.bunifuButton2.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuButton2.BackgroundImage")));
            this.bunifuButton2.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton2.ButtonText = "Hủy";
            this.bunifuButton2.ButtonTextMarginLeft = 0;
            this.bunifuButton2.ColorContrastOnClick = 45;
            this.bunifuButton2.ColorContrastOnHover = 45;
            this.bunifuButton2.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges4.BottomLeft = true;
            borderEdges4.BottomRight = true;
            borderEdges4.TopLeft = true;
            borderEdges4.TopRight = true;
            this.bunifuButton2.CustomizableEdges = borderEdges4;
            this.bunifuButton2.DialogResult = System.Windows.Forms.DialogResult.None;
            this.bunifuButton2.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.bunifuButton2.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bunifuButton2.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.bunifuButton2.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.bunifuButton2.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.bunifuButton2.ForeColor = System.Drawing.Color.White;
            this.bunifuButton2.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.bunifuButton2.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.bunifuButton2.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.bunifuButton2.IconMarginLeft = 11;
            this.bunifuButton2.IconPadding = 10;
            this.bunifuButton2.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.bunifuButton2.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.bunifuButton2.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.bunifuButton2.IconSize = 25;
            this.bunifuButton2.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(192)))), ((int)(((byte)(64)))), ((int)(((byte)(0)))));
            this.bunifuButton2.IdleBorderRadius = 1;
            this.bunifuButton2.IdleBorderThickness = 1;
            this.bunifuButton2.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(192)))), ((int)(((byte)(64)))), ((int)(((byte)(0)))));
            this.bunifuButton2.IdleIconLeftImage = null;
            this.bunifuButton2.IdleIconRightImage = null;
            this.bunifuButton2.IndicateFocus = false;
            this.bunifuButton2.Location = new System.Drawing.Point(344, 581);
            this.bunifuButton2.Name = "bunifuButton2";
            this.bunifuButton2.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.bunifuButton2.OnDisabledState.BorderRadius = 1;
            this.bunifuButton2.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton2.OnDisabledState.BorderThickness = 1;
            this.bunifuButton2.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bunifuButton2.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.bunifuButton2.OnDisabledState.IconLeftImage = null;
            this.bunifuButton2.OnDisabledState.IconRightImage = null;
            this.bunifuButton2.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.bunifuButton2.onHoverState.BorderRadius = 1;
            this.bunifuButton2.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton2.onHoverState.BorderThickness = 1;
            this.bunifuButton2.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.bunifuButton2.onHoverState.ForeColor = System.Drawing.Color.White;
            this.bunifuButton2.onHoverState.IconLeftImage = null;
            this.bunifuButton2.onHoverState.IconRightImage = null;
            this.bunifuButton2.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(192)))), ((int)(((byte)(64)))), ((int)(((byte)(0)))));
            this.bunifuButton2.OnIdleState.BorderRadius = 1;
            this.bunifuButton2.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton2.OnIdleState.BorderThickness = 1;
            this.bunifuButton2.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(192)))), ((int)(((byte)(64)))), ((int)(((byte)(0)))));
            this.bunifuButton2.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.bunifuButton2.OnIdleState.IconLeftImage = null;
            this.bunifuButton2.OnIdleState.IconRightImage = null;
            this.bunifuButton2.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.bunifuButton2.OnPressedState.BorderRadius = 1;
            this.bunifuButton2.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton2.OnPressedState.BorderThickness = 1;
            this.bunifuButton2.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.bunifuButton2.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.bunifuButton2.OnPressedState.IconLeftImage = null;
            this.bunifuButton2.OnPressedState.IconRightImage = null;
            this.bunifuButton2.Size = new System.Drawing.Size(89, 39);
            this.bunifuButton2.TabIndex = 13;
            this.bunifuButton2.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.bunifuButton2.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.bunifuButton2.TextMarginLeft = 0;
            this.bunifuButton2.TextPadding = new System.Windows.Forms.Padding(0);
            this.bunifuButton2.UseDefaultRadiusAndThickness = true;
            this.bunifuButton2.Click += new System.EventHandler(this.bunifuButton2_Click);
            // 
            // CN
            // 
            this.CN.AcceptsReturn = false;
            this.CN.AcceptsTab = false;
            this.CN.AnimationSpeed = 200;
            this.CN.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.CN.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.CN.BackColor = System.Drawing.Color.Transparent;
            this.CN.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("CN.BackgroundImage")));
            this.CN.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.CN.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.CN.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.CN.BorderColorIdle = System.Drawing.Color.Silver;
            this.CN.BorderRadius = 1;
            this.CN.BorderThickness = 1;
            this.CN.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.CN.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.CN.DefaultFont = new System.Drawing.Font("Times New Roman", 9F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.CN.DefaultText = "";
            this.CN.FillColor = System.Drawing.Color.White;
            this.CN.HideSelection = true;
            this.CN.IconLeft = null;
            this.CN.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.CN.IconPadding = 10;
            this.CN.IconRight = null;
            this.CN.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.CN.Lines = new string[0];
            this.CN.Location = new System.Drawing.Point(907, 359);
            this.CN.MaxLength = 32767;
            this.CN.MinimumSize = new System.Drawing.Size(1, 1);
            this.CN.Modified = false;
            this.CN.Multiline = false;
            this.CN.Name = "CN";
            stateProperties49.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties49.FillColor = System.Drawing.Color.Empty;
            stateProperties49.ForeColor = System.Drawing.Color.Empty;
            stateProperties49.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.CN.OnActiveState = stateProperties49;
            stateProperties50.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties50.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties50.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties50.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.CN.OnDisabledState = stateProperties50;
            stateProperties51.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties51.FillColor = System.Drawing.Color.Empty;
            stateProperties51.ForeColor = System.Drawing.Color.Empty;
            stateProperties51.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.CN.OnHoverState = stateProperties51;
            stateProperties52.BorderColor = System.Drawing.Color.Silver;
            stateProperties52.FillColor = System.Drawing.Color.White;
            stateProperties52.ForeColor = System.Drawing.Color.Empty;
            stateProperties52.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.CN.OnIdleState = stateProperties52;
            this.CN.Padding = new System.Windows.Forms.Padding(3);
            this.CN.PasswordChar = '\0';
            this.CN.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.CN.PlaceholderText = "Nhập chuyên ngành";
            this.CN.ReadOnly = false;
            this.CN.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.CN.SelectedText = "";
            this.CN.SelectionLength = 0;
            this.CN.SelectionStart = 0;
            this.CN.ShortcutsEnabled = true;
            this.CN.Size = new System.Drawing.Size(260, 34);
            this.CN.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.CN.TabIndex = 8;
            this.CN.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.CN.TextMarginBottom = 0;
            this.CN.TextMarginLeft = 3;
            this.CN.TextMarginTop = 0;
            this.CN.TextPlaceholder = "Nhập chuyên ngành";
            this.CN.UseSystemPasswordChar = false;
            this.CN.WordWrap = true;
            // 
            // TT
            // 
            this.TT.BackColor = System.Drawing.Color.Transparent;
            this.TT.DrawMode = System.Windows.Forms.DrawMode.OwnerDrawFixed;
            this.TT.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.TT.FocusedColor = System.Drawing.Color.FromArgb(((int)(((byte)(94)))), ((int)(((byte)(148)))), ((int)(((byte)(255)))));
            this.TT.FocusedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(94)))), ((int)(((byte)(148)))), ((int)(((byte)(255)))));
            this.TT.FocusedState.Parent = this.TT;
            this.TT.Font = new System.Drawing.Font("Segoe UI", 10F);
            this.TT.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(68)))), ((int)(((byte)(88)))), ((int)(((byte)(112)))));
            this.TT.HoverState.Parent = this.TT;
            this.TT.ItemHeight = 30;
            this.TT.Items.AddRange(new object[] {
            "Chờ phê duyệt",
            "Đang làm",
            "Đã hoàn thành"});
            this.TT.ItemsAppearance.Parent = this.TT;
            this.TT.Location = new System.Drawing.Point(531, 359);
            this.TT.Name = "TT";
            this.TT.ShadowDecoration.Parent = this.TT;
            this.TT.Size = new System.Drawing.Size(260, 36);
            this.TT.TabIndex = 14;
            this.TT.SelectedIndexChanged += new System.EventHandler(this.TT_SelectedIndexChanged);
            // 
            // TenDT
            // 
            this.TenDT.AcceptsReturn = false;
            this.TenDT.AcceptsTab = false;
            this.TenDT.AnimationSpeed = 200;
            this.TenDT.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.TenDT.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.TenDT.BackColor = System.Drawing.Color.Transparent;
            this.TenDT.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("TenDT.BackgroundImage")));
            this.TenDT.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.TenDT.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.TenDT.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.TenDT.BorderColorIdle = System.Drawing.Color.Silver;
            this.TenDT.BorderRadius = 1;
            this.TenDT.BorderThickness = 1;
            this.TenDT.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.TenDT.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.TenDT.DefaultFont = new System.Drawing.Font("Times New Roman", 9F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.TenDT.DefaultText = "";
            this.TenDT.FillColor = System.Drawing.Color.White;
            this.TenDT.HideSelection = true;
            this.TenDT.IconLeft = null;
            this.TenDT.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.TenDT.IconPadding = 10;
            this.TenDT.IconRight = null;
            this.TenDT.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.TenDT.Lines = new string[0];
            this.TenDT.Location = new System.Drawing.Point(531, 127);
            this.TenDT.MaxLength = 32767;
            this.TenDT.MinimumSize = new System.Drawing.Size(1, 1);
            this.TenDT.Modified = false;
            this.TenDT.Multiline = false;
            this.TenDT.Name = "TenDT";
            stateProperties53.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties53.FillColor = System.Drawing.Color.Empty;
            stateProperties53.ForeColor = System.Drawing.Color.Empty;
            stateProperties53.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.TenDT.OnActiveState = stateProperties53;
            stateProperties54.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties54.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties54.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties54.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.TenDT.OnDisabledState = stateProperties54;
            stateProperties55.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties55.FillColor = System.Drawing.Color.Empty;
            stateProperties55.ForeColor = System.Drawing.Color.Empty;
            stateProperties55.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.TenDT.OnHoverState = stateProperties55;
            stateProperties56.BorderColor = System.Drawing.Color.Silver;
            stateProperties56.FillColor = System.Drawing.Color.White;
            stateProperties56.ForeColor = System.Drawing.Color.Empty;
            stateProperties56.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.TenDT.OnIdleState = stateProperties56;
            this.TenDT.Padding = new System.Windows.Forms.Padding(3);
            this.TenDT.PasswordChar = '\0';
            this.TenDT.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.TenDT.PlaceholderText = "Nhập tên đề tài";
            this.TenDT.ReadOnly = false;
            this.TenDT.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.TenDT.SelectedText = "";
            this.TenDT.SelectionLength = 0;
            this.TenDT.SelectionStart = 0;
            this.TenDT.ShortcutsEnabled = true;
            this.TenDT.Size = new System.Drawing.Size(260, 34);
            this.TenDT.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.TenDT.TabIndex = 4;
            this.TenDT.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.TenDT.TextMarginBottom = 0;
            this.TenDT.TextMarginLeft = 3;
            this.TenDT.TextMarginTop = 0;
            this.TenDT.TextPlaceholder = "Nhập tên đề tài";
            this.TenDT.UseSystemPasswordChar = false;
            this.TenDT.WordWrap = true;
            // 
            // MDT
            // 
            this.MDT.AcceptsReturn = false;
            this.MDT.AcceptsTab = false;
            this.MDT.AnimationSpeed = 200;
            this.MDT.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.MDT.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.MDT.BackColor = System.Drawing.Color.Transparent;
            this.MDT.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("MDT.BackgroundImage")));
            this.MDT.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.MDT.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.MDT.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.MDT.BorderColorIdle = System.Drawing.Color.Silver;
            this.MDT.BorderRadius = 1;
            this.MDT.BorderThickness = 1;
            this.MDT.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.MDT.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.MDT.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.MDT.DefaultText = "";
            this.MDT.FillColor = System.Drawing.Color.White;
            this.MDT.HideSelection = true;
            this.MDT.IconLeft = null;
            this.MDT.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.MDT.IconPadding = 10;
            this.MDT.IconRight = null;
            this.MDT.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.MDT.Lines = new string[0];
            this.MDT.Location = new System.Drawing.Point(173, 126);
            this.MDT.MaxLength = 32767;
            this.MDT.MinimumSize = new System.Drawing.Size(1, 1);
            this.MDT.Modified = false;
            this.MDT.Multiline = false;
            this.MDT.Name = "MDT";
            stateProperties57.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties57.FillColor = System.Drawing.Color.Empty;
            stateProperties57.ForeColor = System.Drawing.Color.Empty;
            stateProperties57.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.MDT.OnActiveState = stateProperties57;
            stateProperties58.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties58.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties58.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties58.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.MDT.OnDisabledState = stateProperties58;
            stateProperties59.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties59.FillColor = System.Drawing.Color.Empty;
            stateProperties59.ForeColor = System.Drawing.Color.Empty;
            stateProperties59.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.MDT.OnHoverState = stateProperties59;
            stateProperties60.BorderColor = System.Drawing.Color.Silver;
            stateProperties60.FillColor = System.Drawing.Color.White;
            stateProperties60.ForeColor = System.Drawing.Color.Empty;
            stateProperties60.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.MDT.OnIdleState = stateProperties60;
            this.MDT.Padding = new System.Windows.Forms.Padding(3);
            this.MDT.PasswordChar = '\0';
            this.MDT.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.MDT.PlaceholderText = "Nhập mã đề tài";
            this.MDT.ReadOnly = false;
            this.MDT.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.MDT.SelectedText = "";
            this.MDT.SelectionLength = 0;
            this.MDT.SelectionStart = 0;
            this.MDT.ShortcutsEnabled = true;
            this.MDT.Size = new System.Drawing.Size(260, 37);
            this.MDT.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.MDT.TabIndex = 0;
            this.MDT.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.MDT.TextMarginBottom = 0;
            this.MDT.TextMarginLeft = 3;
            this.MDT.TextMarginTop = 0;
            this.MDT.TextPlaceholder = "Nhập mã đề tài";
            this.MDT.UseSystemPasswordChar = false;
            this.MDT.WordWrap = true;
            // 
            // panel2
            // 
            this.panel2.Controls.Add(this.guna2HtmlLabel2);
            this.panel2.Controls.Add(this.NgayBD);
            this.panel2.Controls.Add(this.NgayNT);
            this.panel2.Controls.Add(this.TienDo);
            this.panel2.Controls.Add(this.KQ);
            this.panel2.Controls.Add(this.MDT);
            this.panel2.Controls.Add(this.TenDT);
            this.panel2.Controls.Add(this.TT);
            this.panel2.Controls.Add(this.CN);
            this.panel2.Controls.Add(this.bunifuButton2);
            this.panel2.Controls.Add(this.LSP);
            this.panel2.Controls.Add(this.HT);
            this.panel2.Controls.Add(this.MBM);
            this.panel2.Controls.Add(this.Cap);
            this.panel2.Dock = System.Windows.Forms.DockStyle.Left;
            this.panel2.Location = new System.Drawing.Point(0, 0);
            this.panel2.Name = "panel2";
            this.panel2.Size = new System.Drawing.Size(1440, 744);
            this.panel2.TabIndex = 16;
            // 
            // NgayBD
            // 
            this.NgayBD.AcceptsReturn = false;
            this.NgayBD.AcceptsTab = false;
            this.NgayBD.AnimationSpeed = 200;
            this.NgayBD.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.NgayBD.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.NgayBD.BackColor = System.Drawing.Color.Transparent;
            this.NgayBD.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("NgayBD.BackgroundImage")));
            this.NgayBD.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.NgayBD.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.NgayBD.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.NgayBD.BorderColorIdle = System.Drawing.Color.Silver;
            this.NgayBD.BorderRadius = 1;
            this.NgayBD.BorderThickness = 1;
            this.NgayBD.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.NgayBD.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.NgayBD.DefaultFont = new System.Drawing.Font("Times New Roman", 9F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.NgayBD.DefaultText = "";
            this.NgayBD.FillColor = System.Drawing.Color.White;
            this.NgayBD.HideSelection = true;
            this.NgayBD.IconLeft = null;
            this.NgayBD.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.NgayBD.IconPadding = 10;
            this.NgayBD.IconRight = null;
            this.NgayBD.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.NgayBD.Lines = new string[0];
            this.NgayBD.Location = new System.Drawing.Point(531, 470);
            this.NgayBD.MaxLength = 32767;
            this.NgayBD.MinimumSize = new System.Drawing.Size(1, 1);
            this.NgayBD.Modified = false;
            this.NgayBD.Multiline = false;
            this.NgayBD.Name = "NgayBD";
            stateProperties61.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties61.FillColor = System.Drawing.Color.Empty;
            stateProperties61.ForeColor = System.Drawing.Color.Empty;
            stateProperties61.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.NgayBD.OnActiveState = stateProperties61;
            stateProperties62.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties62.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties62.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties62.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.NgayBD.OnDisabledState = stateProperties62;
            stateProperties63.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties63.FillColor = System.Drawing.Color.Empty;
            stateProperties63.ForeColor = System.Drawing.Color.Empty;
            stateProperties63.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.NgayBD.OnHoverState = stateProperties63;
            stateProperties64.BorderColor = System.Drawing.Color.Silver;
            stateProperties64.FillColor = System.Drawing.Color.White;
            stateProperties64.ForeColor = System.Drawing.Color.Empty;
            stateProperties64.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.NgayBD.OnIdleState = stateProperties64;
            this.NgayBD.Padding = new System.Windows.Forms.Padding(3);
            this.NgayBD.PasswordChar = '\0';
            this.NgayBD.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.NgayBD.PlaceholderText = "Ngày bắt đầu";
            this.NgayBD.ReadOnly = false;
            this.NgayBD.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.NgayBD.SelectedText = "";
            this.NgayBD.SelectionLength = 0;
            this.NgayBD.SelectionStart = 0;
            this.NgayBD.ShortcutsEnabled = true;
            this.NgayBD.Size = new System.Drawing.Size(260, 34);
            this.NgayBD.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.NgayBD.TabIndex = 19;
            this.NgayBD.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.NgayBD.TextMarginBottom = 0;
            this.NgayBD.TextMarginLeft = 3;
            this.NgayBD.TextMarginTop = 0;
            this.NgayBD.TextPlaceholder = "Ngày bắt đầu";
            this.NgayBD.UseSystemPasswordChar = false;
            this.NgayBD.WordWrap = true;
            // 
            // NgayNT
            // 
            this.NgayNT.AcceptsReturn = false;
            this.NgayNT.AcceptsTab = false;
            this.NgayNT.AnimationSpeed = 200;
            this.NgayNT.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.NgayNT.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.NgayNT.BackColor = System.Drawing.Color.Transparent;
            this.NgayNT.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("NgayNT.BackgroundImage")));
            this.NgayNT.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.NgayNT.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.NgayNT.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.NgayNT.BorderColorIdle = System.Drawing.Color.Silver;
            this.NgayNT.BorderRadius = 1;
            this.NgayNT.BorderThickness = 1;
            this.NgayNT.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.NgayNT.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.NgayNT.DefaultFont = new System.Drawing.Font("Times New Roman", 9F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.NgayNT.DefaultText = "";
            this.NgayNT.FillColor = System.Drawing.Color.White;
            this.NgayNT.HideSelection = true;
            this.NgayNT.IconLeft = null;
            this.NgayNT.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.NgayNT.IconPadding = 10;
            this.NgayNT.IconRight = null;
            this.NgayNT.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.NgayNT.Lines = new string[0];
            this.NgayNT.Location = new System.Drawing.Point(173, 470);
            this.NgayNT.MaxLength = 32767;
            this.NgayNT.MinimumSize = new System.Drawing.Size(1, 1);
            this.NgayNT.Modified = false;
            this.NgayNT.Multiline = false;
            this.NgayNT.Name = "NgayNT";
            stateProperties65.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties65.FillColor = System.Drawing.Color.Empty;
            stateProperties65.ForeColor = System.Drawing.Color.Empty;
            stateProperties65.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.NgayNT.OnActiveState = stateProperties65;
            stateProperties66.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties66.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties66.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties66.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.NgayNT.OnDisabledState = stateProperties66;
            stateProperties67.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties67.FillColor = System.Drawing.Color.Empty;
            stateProperties67.ForeColor = System.Drawing.Color.Empty;
            stateProperties67.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.NgayNT.OnHoverState = stateProperties67;
            stateProperties68.BorderColor = System.Drawing.Color.Silver;
            stateProperties68.FillColor = System.Drawing.Color.White;
            stateProperties68.ForeColor = System.Drawing.Color.Empty;
            stateProperties68.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.NgayNT.OnIdleState = stateProperties68;
            this.NgayNT.Padding = new System.Windows.Forms.Padding(3);
            this.NgayNT.PasswordChar = '\0';
            this.NgayNT.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.NgayNT.PlaceholderText = "Nhập chuyên ngành";
            this.NgayNT.ReadOnly = false;
            this.NgayNT.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.NgayNT.SelectedText = "";
            this.NgayNT.SelectionLength = 0;
            this.NgayNT.SelectionStart = 0;
            this.NgayNT.ShortcutsEnabled = true;
            this.NgayNT.Size = new System.Drawing.Size(260, 34);
            this.NgayNT.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.NgayNT.TabIndex = 18;
            this.NgayNT.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.NgayNT.TextMarginBottom = 0;
            this.NgayNT.TextMarginLeft = 3;
            this.NgayNT.TextMarginTop = 0;
            this.NgayNT.TextPlaceholder = "Nhập chuyên ngành";
            this.NgayNT.UseSystemPasswordChar = false;
            this.NgayNT.WordWrap = true;
            // 
            // TienDo
            // 
            this.TienDo.AcceptsReturn = false;
            this.TienDo.AcceptsTab = false;
            this.TienDo.AnimationSpeed = 200;
            this.TienDo.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.TienDo.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.TienDo.BackColor = System.Drawing.Color.Transparent;
            this.TienDo.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("TienDo.BackgroundImage")));
            this.TienDo.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.TienDo.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.TienDo.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.TienDo.BorderColorIdle = System.Drawing.Color.Silver;
            this.TienDo.BorderRadius = 1;
            this.TienDo.BorderThickness = 1;
            this.TienDo.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.TienDo.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.TienDo.DefaultFont = new System.Drawing.Font("Times New Roman", 9F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.TienDo.DefaultText = "";
            this.TienDo.FillColor = System.Drawing.Color.White;
            this.TienDo.HideSelection = true;
            this.TienDo.IconLeft = null;
            this.TienDo.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.TienDo.IconPadding = 10;
            this.TienDo.IconRight = null;
            this.TienDo.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.TienDo.Lines = new string[0];
            this.TienDo.Location = new System.Drawing.Point(531, 248);
            this.TienDo.MaxLength = 32767;
            this.TienDo.MinimumSize = new System.Drawing.Size(1, 1);
            this.TienDo.Modified = false;
            this.TienDo.Multiline = false;
            this.TienDo.Name = "TienDo";
            stateProperties69.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties69.FillColor = System.Drawing.Color.Empty;
            stateProperties69.ForeColor = System.Drawing.Color.Empty;
            stateProperties69.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.TienDo.OnActiveState = stateProperties69;
            stateProperties70.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties70.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties70.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties70.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.TienDo.OnDisabledState = stateProperties70;
            stateProperties71.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties71.FillColor = System.Drawing.Color.Empty;
            stateProperties71.ForeColor = System.Drawing.Color.Empty;
            stateProperties71.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.TienDo.OnHoverState = stateProperties71;
            stateProperties72.BorderColor = System.Drawing.Color.Silver;
            stateProperties72.FillColor = System.Drawing.Color.White;
            stateProperties72.ForeColor = System.Drawing.Color.Empty;
            stateProperties72.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.TienDo.OnIdleState = stateProperties72;
            this.TienDo.Padding = new System.Windows.Forms.Padding(3);
            this.TienDo.PasswordChar = '\0';
            this.TienDo.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.TienDo.PlaceholderText = "Tiến độ";
            this.TienDo.ReadOnly = false;
            this.TienDo.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.TienDo.SelectedText = "";
            this.TienDo.SelectionLength = 0;
            this.TienDo.SelectionStart = 0;
            this.TienDo.ShortcutsEnabled = true;
            this.TienDo.Size = new System.Drawing.Size(260, 34);
            this.TienDo.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.TienDo.TabIndex = 16;
            this.TienDo.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.TienDo.TextMarginBottom = 0;
            this.TienDo.TextMarginLeft = 3;
            this.TienDo.TextMarginTop = 0;
            this.TienDo.TextPlaceholder = "Tiến độ";
            this.TienDo.UseSystemPasswordChar = false;
            this.TienDo.WordWrap = true;
            // 
            // KQ
            // 
            this.KQ.AcceptsReturn = false;
            this.KQ.AcceptsTab = false;
            this.KQ.AnimationSpeed = 200;
            this.KQ.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.KQ.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.KQ.BackColor = System.Drawing.Color.Transparent;
            this.KQ.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("KQ.BackgroundImage")));
            this.KQ.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.KQ.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.KQ.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.KQ.BorderColorIdle = System.Drawing.Color.Silver;
            this.KQ.BorderRadius = 1;
            this.KQ.BorderThickness = 1;
            this.KQ.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.KQ.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.KQ.DefaultFont = new System.Drawing.Font("Times New Roman", 9F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.KQ.DefaultText = "";
            this.KQ.FillColor = System.Drawing.Color.White;
            this.KQ.HideSelection = true;
            this.KQ.IconLeft = null;
            this.KQ.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.KQ.IconPadding = 10;
            this.KQ.IconRight = null;
            this.KQ.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.KQ.Lines = new string[0];
            this.KQ.Location = new System.Drawing.Point(907, 248);
            this.KQ.MaxLength = 32767;
            this.KQ.MinimumSize = new System.Drawing.Size(1, 1);
            this.KQ.Modified = false;
            this.KQ.Multiline = false;
            this.KQ.Name = "KQ";
            stateProperties73.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties73.FillColor = System.Drawing.Color.Empty;
            stateProperties73.ForeColor = System.Drawing.Color.Empty;
            stateProperties73.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.KQ.OnActiveState = stateProperties73;
            stateProperties74.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties74.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties74.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties74.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.KQ.OnDisabledState = stateProperties74;
            stateProperties75.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties75.FillColor = System.Drawing.Color.Empty;
            stateProperties75.ForeColor = System.Drawing.Color.Empty;
            stateProperties75.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.KQ.OnHoverState = stateProperties75;
            stateProperties76.BorderColor = System.Drawing.Color.Silver;
            stateProperties76.FillColor = System.Drawing.Color.White;
            stateProperties76.ForeColor = System.Drawing.Color.Empty;
            stateProperties76.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.KQ.OnIdleState = stateProperties76;
            this.KQ.Padding = new System.Windows.Forms.Padding(3);
            this.KQ.PasswordChar = '\0';
            this.KQ.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.KQ.PlaceholderText = "Nhập kết quả";
            this.KQ.ReadOnly = false;
            this.KQ.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.KQ.SelectedText = "";
            this.KQ.SelectionLength = 0;
            this.KQ.SelectionStart = 0;
            this.KQ.ShortcutsEnabled = true;
            this.KQ.Size = new System.Drawing.Size(260, 34);
            this.KQ.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.KQ.TabIndex = 15;
            this.KQ.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.KQ.TextMarginBottom = 0;
            this.KQ.TextMarginLeft = 3;
            this.KQ.TextMarginTop = 0;
            this.KQ.TextPlaceholder = "Nhập kết quả";
            this.KQ.UseSystemPasswordChar = false;
            this.KQ.WordWrap = true;
            // 
            // LSP
            // 
            this.LSP.AcceptsReturn = false;
            this.LSP.AcceptsTab = false;
            this.LSP.AnimationSpeed = 200;
            this.LSP.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.LSP.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.LSP.BackColor = System.Drawing.Color.Transparent;
            this.LSP.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("LSP.BackgroundImage")));
            this.LSP.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.LSP.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.LSP.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.LSP.BorderColorIdle = System.Drawing.Color.Silver;
            this.LSP.BorderRadius = 1;
            this.LSP.BorderThickness = 1;
            this.LSP.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.LSP.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.LSP.DefaultFont = new System.Drawing.Font("Times New Roman", 9F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.LSP.DefaultText = "";
            this.LSP.FillColor = System.Drawing.Color.White;
            this.LSP.HideSelection = true;
            this.LSP.IconLeft = null;
            this.LSP.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.LSP.IconPadding = 10;
            this.LSP.IconRight = null;
            this.LSP.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.LSP.Lines = new string[0];
            this.LSP.Location = new System.Drawing.Point(173, 358);
            this.LSP.MaxLength = 32767;
            this.LSP.MinimumSize = new System.Drawing.Size(1, 1);
            this.LSP.Modified = false;
            this.LSP.Multiline = false;
            this.LSP.Name = "LSP";
            stateProperties77.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties77.FillColor = System.Drawing.Color.Empty;
            stateProperties77.ForeColor = System.Drawing.Color.Empty;
            stateProperties77.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.LSP.OnActiveState = stateProperties77;
            stateProperties78.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties78.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties78.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties78.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.LSP.OnDisabledState = stateProperties78;
            stateProperties79.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties79.FillColor = System.Drawing.Color.Empty;
            stateProperties79.ForeColor = System.Drawing.Color.Empty;
            stateProperties79.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.LSP.OnHoverState = stateProperties79;
            stateProperties80.BorderColor = System.Drawing.Color.Silver;
            stateProperties80.FillColor = System.Drawing.Color.White;
            stateProperties80.ForeColor = System.Drawing.Color.Empty;
            stateProperties80.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.LSP.OnIdleState = stateProperties80;
            this.LSP.Padding = new System.Windows.Forms.Padding(3);
            this.LSP.PasswordChar = '\0';
            this.LSP.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.LSP.PlaceholderText = "Nhập loại sản phẩm";
            this.LSP.ReadOnly = false;
            this.LSP.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.LSP.SelectedText = "";
            this.LSP.SelectionLength = 0;
            this.LSP.SelectionStart = 0;
            this.LSP.ShortcutsEnabled = true;
            this.LSP.Size = new System.Drawing.Size(260, 34);
            this.LSP.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.LSP.TabIndex = 10;
            this.LSP.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.LSP.TextMarginBottom = 0;
            this.LSP.TextMarginLeft = 3;
            this.LSP.TextMarginTop = 0;
            this.LSP.TextPlaceholder = "Nhập loại sản phẩm";
            this.LSP.UseSystemPasswordChar = false;
            this.LSP.WordWrap = true;
            // 
            // guna2HtmlLabel2
            // 
            this.guna2HtmlLabel2.BackColor = System.Drawing.Color.Transparent;
            this.guna2HtmlLabel2.Font = new System.Drawing.Font("Times New Roman", 21.75F, System.Drawing.FontStyle.Italic, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.guna2HtmlLabel2.Location = new System.Drawing.Point(513, 32);
            this.guna2HtmlLabel2.Name = "guna2HtmlLabel2";
            this.guna2HtmlLabel2.Size = new System.Drawing.Size(376, 36);
            this.guna2HtmlLabel2.TabIndex = 21;
            this.guna2HtmlLabel2.Text = "Sửa đề tài nghiên cứu khoa học\r\n";
            // 
            // modal
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.ClientSize = new System.Drawing.Size(1443, 744);
            this.Controls.Add(this.panel2);
            this.Name = "modal";
            this.Text = " ";
            this.panel2.ResumeLayout(false);
            this.panel2.PerformLayout();
            this.ResumeLayout(false);

        }

        #endregion
        private Bunifu.UI.WinForms.BunifuTextBox Cap;
        private Bunifu.UI.WinForms.BunifuTextBox MBM;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton HT;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton bunifuButton2;
        private Bunifu.UI.WinForms.BunifuTextBox CN;
        private Guna.UI2.WinForms.Guna2ComboBox TT;
        private Bunifu.UI.WinForms.BunifuTextBox TenDT;
        private Bunifu.UI.WinForms.BunifuTextBox MDT;
        private System.Windows.Forms.Panel panel2;
        private Bunifu.UI.WinForms.BunifuTextBox LSP;
        private Bunifu.UI.WinForms.BunifuTextBox NgayNT;
        private Bunifu.UI.WinForms.BunifuTextBox TienDo;
        private Bunifu.UI.WinForms.BunifuTextBox KQ;
        private Bunifu.UI.WinForms.BunifuTextBox NgayBD;
        private Guna.UI2.WinForms.Guna2HtmlLabel guna2HtmlLabel2;
    }
}